import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Stitch Design System tokens ──
        primary:                    "#005da8",
        "on-primary":               "#ffffff",
        "primary-container":        "#0076d2",
        "on-primary-container":     "#fdfcff",
        "primary-fixed":            "#d4e3ff",
        "primary-fixed-dim":        "#a4c9ff",
        "on-primary-fixed":         "#001c39",
        "on-primary-fixed-variant": "#004883",
        "inverse-primary":          "#a4c9ff",
        secondary:                  "#725c00",
        "on-secondary":             "#ffffff",
        "secondary-container":      "#fdd000",
        "on-secondary-container":   "#6e5900",
        "secondary-fixed":          "#ffe07c",
        "secondary-fixed-dim":      "#ecc200",
        "on-secondary-fixed":       "#231b00",
        "on-secondary-fixed-variant": "#564500",
        tertiary:                   "#ae0f76",
        "on-tertiary":              "#ffffff",
        "tertiary-container":       "#cf3390",
        "on-tertiary-container":    "#fffbff",
        "tertiary-fixed":           "#ffd8e7",
        "tertiary-fixed-dim":       "#ffafd4",
        "on-tertiary-fixed":        "#3d0026",
        "on-tertiary-fixed-variant": "#8b005d",
        surface:                    "#f4fafd",
        "surface-dim":              "#d4dbdd",
        "surface-bright":           "#f4fafd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#eef5f7",
        "surface-container":        "#e8eff1",
        "surface-container-high":   "#e2e9ec",
        "surface-container-highest":"#dde4e6",
        "surface-variant":          "#dde4e6",
        "surface-tint":             "#005fac",
        "on-surface":               "#161d1f",
        "on-surface-variant":       "#404753",
        "inverse-surface":          "#2b3234",
        "inverse-on-surface":       "#ebf2f4",
        outline:                    "#707785",
        "outline-variant":          "#c0c7d6",
        error:                      "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
        background:                 "#f4fafd",
        "on-background":            "#161d1f",
        // ── Legacy brand aliases (kept for backward compat) ──
        brand: {
          blue:         "#005da8",
          "blue-light": "#0076d2",
          purple:       "#ae0f76",
          orange:       "#f97316",
          yellow:       "#fdd000",
          pink:         "#cf3390",
          teal:         "#14b8a6",
          green:        "#22c55e",
          navy:         "#1e3a8a",
        },
      },
      fontFamily: {
        sans:    ["Work Sans", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg:  "var(--radius)",
        md:  "calc(var(--radius) - 2px)",
        sm:  "calc(var(--radius) - 4px)",
      },
      animation: {
        "fade-in":       "fadeIn 0.5s ease-in-out",
        "slide-up":      "slideUp 0.5s ease-out",
        "slide-down":    "slideDown 0.3s ease-out",
        float:           "float 6s ease-in-out infinite",
        "pulse-slow":    "pulse 3s ease-in-out infinite",
        "gradient-shift":"gradientShift 8s ease infinite",
        "bounce-slow":   "bounce 2s infinite",
        wiggle:          "wiggle 1s ease-in-out infinite",
      },
      keyframes: {
        fadeIn:        { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp:       { "0%": { transform: "translateY(20px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        slideDown:     { "0%": { transform: "translateY(-10px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        float:         { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-10px)" } },
        gradientShift: { "0%, 100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        wiggle:        { "0%, 100%": { transform: "rotate(-3deg)" }, "50%": { transform: "rotate(3deg)" } },
      },
      backgroundSize: { "300%": "300%" },
      boxShadow: {
        glow:          "0 0 20px rgba(0, 93, 168, 0.30)",
        "glow-blue":   "0 0 20px rgba(0, 93, 168, 0.30)",
        "glow-yellow": "0 0 20px rgba(253, 208, 0, 0.50)",
        card:          "0 4px 24px rgba(0, 93, 168, 0.08)",
        "card-hover":  "0 8px 40px rgba(0, 93, 168, 0.14)",
      },
    },
  },
  plugins: [],
};

export default config;
